// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    Homeview: typeof import('./views/HomeView/Homeview.vue')['default']
    HomeView: typeof import('./views/HomeView/HomeView.vue')['default']
    LoadingModal: typeof import('./components/LoadingModal/LoadingModal.vue')['default']
    LoginForm: typeof import('./components/LoginForm/LoginForm.vue')['default']
    MarketView: typeof import('./views/MarketView/MarketView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextModal: typeof import('./components/TextModal/TextModal.vue')['default']
    WelcomeText: typeof import('./components/WelcomeText/WelcomeText.vue')['default']
  }
}
